name: flutter_core_unique_id
description: "A new Flutter plugin for getting the Unique ID."
version: 1.0.1

repository: https://github.com/ShareAnTalk/flutter-unique-id
issue_tracker: https://github.com/ShareAnTalk/flutter-unique-id/issues

maintainer: ShareInvest Corp.

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.shareinvest.unique_id
        pluginClass: UniqueIdPlugin
      ios:
        pluginClass: UniqueIdPlugin
